title: 3407 Wild Cards
description: FRC Team 3407's website for information, events, etc.
theme: minima
minima:
  nav_pages:
    - index.md
    - IContact.md
  skin: dark

github:
  is_project_page: false
exclude:
  - README.md
  - LICENSE
