title: 3407 Wild Cards
description: FRC Team 3407's website for information, events, etc.
# theme: minima
remote_theme: "jekyll/minima"

minima:
  nav_pages:
    - index.md
    - jEvents.md
  skin: solarized-dark

github:
  is_project_page: false
exclude:
  - README.md
  - LICENSE
