title: 3407 Wild Cards
description: FRC Team 3407's website for information, events, etc.
remote_theme: jekyll/minima

minima:
  nav_pages:
    - index.md
    - jEvents.md
    - kSponsors.md
    - lContact.md
  skin: light

github:
  is_project_page: false
exclude:
  - README.md
  - LICENSE
